export const BlogCardData = [
  {
    date: "2025-12-28",
    id: "cmjptsyop6t6p07ocwvgsgjho",
    publishedAt: null,
    slug: "google-gen-ai-leader-certification-study-notes",
    title: "Google Gen AI Leader Certification: Study Notes",
    updatedAt: "2025-12-28T15:02:30.231632+00:00",
    description: null,
    views: 3,
    tags: ["Gen AI", "Google Cloud", "Google"],
    image: null,
  },
  {
    date: "2024-10-20",
    id: "cm2hs35551chn07pin9ya6fe7",
    publishedAt: null,
    slug: "html-entities-a-guide-to-displaying-special-characters-in-web-pages",
    title:
      "HTML Entities: A Guide to Displaying Special Characters in Web Pages",
    updatedAt: "2025-12-28T15:20:59.775543+00:00",
    description: null,
    views: 1519,
    tags: ["HTML"],
    image: null,
  },
  {
    date: "2023-12-02",
    id: "clpnmrlb90gzw0bo51bcojvh1",
    publishedAt: null,
    slug: "building-a-download-button-for-pdfs-in-nextjs",
    title: "Building a Download Button for PDFs in Next.js",
    updatedAt: "2025-12-28T15:21:14.773273+00:00",
    description:
      "Next.js provides a powerful and flexible framework for building React applications. In this guide, we'll walk through the process of creating a download button that allows users to download a PDF file in your Next.js app.",
    views: 1657,
    tags: ["next js "],
    image: null,
  },
  {
    date: "2023-10-19",
    id: "clnwrus773ujv0aplm3x6guhb",
    publishedAt: null,
    slug: "docker-quick-start-common-commands",
    title: "Docker Quick Start: Common Commands",
    updatedAt: "2025-12-28T15:21:06.647709+00:00",
    description:
      "This will run the “hello-world” image and display a message indicating that Docker has been successfully installed and is working properly.",
    views: 1596,
    tags: ["docker"],
    image: {
      id: "clnwrujp73uid0aplj5ndgg2w",
      url: "https://ap-south-1.graphassets.com/AjKdICH5Q62FBUaOa173sz/34fwXTTuTIiW6erX25ry",
    },
  },
  {
    date: "2023-10-17",
    id: "clnuavyvb2pha0aplm1wvfpfh",
    publishedAt: null,
    slug: "getting-started-with-git-a-beginners-guide-to-common-git-commands",
    title:
      "Getting Started with Git: A Beginner’s Guide to Common Git Commands",
    updatedAt: "2025-12-28T15:21:10.259514+00:00",
    description:
      "Git is a distributed version control system that helps developers track changes in their code and collaborate seamlessly",
    views: 1566,
    tags: ["git ", "commands"],
    image: {
      id: "clnwrqa133uaz0apluf3ymwgb",
      url: "https://ap-south-1.graphassets.com/AjKdICH5Q62FBUaOa173sz/Ie04iA6FSLOFPyeHgJgI",
    },
  },
];

export const CertificationsData = [
  {
    id: 1,
    name: "Generative AI Leader Certification",
    issuer: "Google",
    issueDate: "2025-12",
    expirationDate: "2028-12",
    credentialUrl: "REPLACE_WITH_ACTUAL_URL_1",
    credentialId: null,
    logoImage: "/images/logos/google.png",
    skills: [],
  },
  {
    id: 2,
    name: "Associate Cloud Engineer",
    issuer: "Google Cloud",
    issueDate: "2023-04",
    expirationDate: "2026-04",
    credentialUrl: "REPLACE_WITH_ACTUAL_URL_2",
    credentialId: "72429634",
    logoImage: "/images/logos/google-cloud.png",
    skills: [],
  },
  {
    id: 3,
    name: "Udemy Labs – Docker for the Absolute Beginner",
    issuer: "KodeKloud",
    issueDate: "2023-03",
    expirationDate: null,
    credentialUrl: "REPLACE_WITH_ACTUAL_URL_3",
    credentialId: "2D0675177693-2D0FACE65248-2D066EE465EB",
    logoImage: "/images/logos/kodekloud.png",
    skills: ["Docker"],
  },
  {
    id: 4,
    name: "Microsoft Certified: Azure Fundamentals",
    issuer: "Microsoft",
    issueDate: "2022-08",
    expirationDate: null,
    credentialUrl: "REPLACE_WITH_ACTUAL_URL_4",
    credentialId: null,
    logoImage: "/images/logos/microsoft.png",
    skills: ["Microsoft Azure"],
  },
  {
    id: 5,
    name: "Microsoft Certified: DevOps Engineer Expert",
    issuer: "Microsoft",
    issueDate: "2023-02",
    expirationDate: "2024-02",
    credentialUrl: "REPLACE_WITH_ACTUAL_URL_5",
    credentialId: null,
    logoImage: "/images/logos/microsoft.png",
    skills: ["Microsoft Azure"],
    status: "Expired",
  },
  {
    id: 6,
    name: "Microsoft Certified: Azure Developer Associate",
    issuer: "Microsoft",
    issueDate: "2023-01",
    expirationDate: "2024-01",
    credentialUrl: "REPLACE_WITH_ACTUAL_URL_6",
    credentialId: null,
    logoImage: "/images/logos/microsoft.png",
    skills: ["Microsoft Azure"],
    status: "Expired",
  },
];
